#!/bin/bash

#
# Simple Nagios plugin to check status of crond
#  Executed via NRPE 

# Path to Crond PID file

pidfile="/var/run/crond.pid"

if [ -e $pidfile ] ; then
        pid=`cat $pidfile`

        if sudo kill -0 $pid  2> /dev/null ;then

               echo "CROND OK: pid $pid running"
               exit 0

        else
                echo "CROND CRITICAL: crond is stopped"
                exit 2
        fi
else
        echo "CROND CRITICAL: crond is stopped"
        exit 2
fi

