#!/bin/bash

#
# Simple script to check status of crond
#

# Path to Crond PID file

pidfile="/var/run/crond.pid"

if [ -e $pidfile ] ; then
        pid=`cat $pidfile`

        if sudo kill -0 $pid  2> /dev/null ;then

               echo "crond is running : pid $pid : OK"
               exit 0

        else
                echo "CROND CRITICAL: crond is stopped"
                exit 2
        fi
else
        echo "CROND CRITICAL: crond is stopped"
        exit 2
fi

